# Generated by Django 4.1.5 on 2023-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('energy_value', models.CharField(max_length=255)),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbo_hydrate', models.IntegerField()),
                ('ingredients', models.CharField(max_length=255)),
                ('cooking_step', models.CharField(max_length=255)),
            ],
        ),
    ]
