# Generated by Django 4.1.5 on 2023-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cooking_step',
            field=models.TextField(),
        ),
    ]
