# Generated by Django 4.1.5 on 2023-01-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_food_cooking_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
