# Generated by Django 4.1.5 on 2023-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
