# Generated by Django 4.1.5 on 2023-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipecategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
