# Generated by Django 4.1.5 on 2023-02-12 10:30

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_product_image_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=recipe.models.upload_to),
        ),
    ]
