# Generated by Django 4.1.5 on 2023-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_recipecategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='images',
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
