# Generated by Django 4.1.5 on 2023-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_recipecategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(upload_to='imagea'),
        ),
    ]
