# Generated by Django 4.1.5 on 2023-02-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_alter_product_image_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='my_recipe',
        ),
    ]
