# Generated by Django 4.1.5 on 2023-02-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_remove_recipe_favorite_remove_recipe_my_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
